server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jsp_test?useUnicode=true&characterEncoding=utf8&SSL=false
    username: root
    password: 80238023
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
    hibernate:
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy